#:schema ./schemas/game.schema.json
name = "Charged Up"
description = "Uwu"
year = 2023
allianceSize = 3

[[elements]]
name = "scoutId"
label = "Scout ID"
screens = ["SubjectiveInfo"]

[elements.field]
fieldType = "Dropdown"
options = ["Red S", "Blue S"]

[[elements]]
name = "teamOneNumber"
label = "Team One Number"
screens = ["SubjectiveInfo"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[elements]]
name = "teamTwoNumber"
label = "Team Two Number"
screens = ["SubjectiveInfo"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[elements]]
name = "teamThreeNumber"
label = "Team Three Number"
screens = ["SubjectiveInfo"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[elements]]
name = "scoutId"
label = "Scout ID"
screens = ["ObjectiveInfo"]

[elements.field]
fieldType = "Dropdown"
options = ["Red 1", "Red 2", "Red 3", "Blue 1", "Blue 2", "Blue 3"]

[[elements]]
name = "matchType"
label = "Match Type"
screens = ["ObjectiveInfo", "SubjectiveInfo"]

[elements.field]
fieldType = "Dropdown"
options = ["Practice", "Qualification", "Quarterfinal", "Semifinal", "Final"]

[[elements]]
name = "matchNumber"
label = "Match Number"
screens = ["ObjectiveInfo", "SubjectiveInfo"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[elements]]
name = "teamNumber"
label = "Team Number"
screens = ["ObjectiveInfo", "PitInfo"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[elements]]
name = "scoutName"
label = "Scout Name"
screens = ["ObjectiveOther", "SubjectiveOther", "PitOther"]

[elements.field]
fieldType = "Text"

[[elements]]
name = "gameElementOne"
label = "Game Element 1"
screens = ["ObjectivePregame"]

[elements.field]
fieldType = "Dropdown"
options = ["Cone", "Cube"]

[[elements]]
name = "gameElementTwo"
label = "Game Element 2"
screens = ["ObjectivePregame"]

[elements.field]
fieldType = "Dropdown"
options = ["Cone", "Cube"]

[[elements]]
name = "gameElementThree"
label = "Game Element 3"
screens = ["ObjectivePregame"]

[elements.field]
fieldType = "Dropdown"
options = ["Cone", "Cube"]

[[elements]]
name = "gameElementFour"
label = "Game Element 4"
screens = ["ObjectivePregame"]

[elements.field]
fieldType = "Dropdown"
options = ["Cone", "Cube"]

[[elements]]
name = "startingPosition"
label = "Starting Position"
screens = ["ObjectivePregame"]

[elements.field]
fieldType = "Dropdown"
options = ["Barrier", "Co-op", "Audience"]

[[elements]]
name = "preload"
label = "Preload"
screens = ["ObjectivePregame"]

[elements.field]
fieldType = "Dropdown"
options = ["Cone", "Cube"]

[[elements]]
name = "autoAttempted"
label = "Auto Attempted"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Boolean"

[[elements]]
name = "conesPickedUp"
label = "Cones Picked Up"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = true
min = 0

[[elements]]
name = "cubesPickedUp"
label = "Cubes Picked Up"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = true
min = 0

[[elements]]
name = "autoCubesTop"
label = "Auto Cubes Top"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = true
min = 0

[[elements]]
name = "autoCubesMiddle"
label = "Auto Cubes Middle"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = true
min = 0

[[elements]]
name = "autoCubesBottom"
label = "Auto Cubes Bottom"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = true
min = 0

[[elements]]
name = "autoConesTop"
label = "Auto Cones Top"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = true
min = 0

[[elements]]
name = "autoConesMiddle"
label = "Auto Cones Middle"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = true
min = 0

[[elements]]
name = "autoConesBottom"
label = "Auto Cones Bottom"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = true
min = 0

[[elements]]
name = "mobilityPointsAchieved"
label = "Mobility Points Achieved"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Boolean"

[[elements]]
name = "endPosition"
label = "End Position"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Dropdown"
options = ["Community", "Outside", "Docked", "Engaged"]

[[elements]]
name = "offensiveCycles"
label = "Offensive Cycles"
screens = ["ObjectiveTeleop"]

[elements.field]
fieldType = "Grouping"

