#:schema ./schemas/game.schema.json
name = "FreightFrenzy"
description = "Ducks Balls Cubes FTC"
year = 2021

[[objectiveElements]]
name = "scoutId"
label = "Scout ID"
screens = ["Info"]

[objectiveElements.field]
fieldType = "Dropdown"
options = ["Red 1", "Red 2", "Red 3", "Blue 1", "Blue 2", "Blue 3"]

[[objectiveElements]]
name = "matchType"
label = "Match Type"
screens = [""]

[objectiveElements.field]
fieldType = "Dropdown"
options = ["Practice", "Qualification", "Quarterfinal", "Semifinal", "Final"]

[[objectiveElements]]
name = "matchNumber"
label = "Match Number"
screens = ["Info"]

[objectiveElements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[objectiveElements]]
name = "teamNumber"
label = "Team Number"
screens = ["Info"]

[objectiveElements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[objectiveElements]]
name = "scoutName"
label = "Scout Name"
screens = ["Postgame"]

[objectiveElements.field]
fieldType = "Text"

[[objectiveElements]]
name = "duckDelivery"
label = "Duck Delivery"
screens = ["Auto", "Endgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "parking"
label = "Parking"
screens = ["Auto", "Postgame"]

[objectiveElements.field]
fieldType = "Dropdown"
options = [
  "None",
  "Warehouse Fully",
  "Warehouse Partially (auto only)",
  "Storage Fully",
  "Storage Partially (auto only)",
]

[[objectiveElements]]
name = "freightShippingHub"
label = "Freight Shipping Hub (any level)"
screens = ["Auto"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "freightStorageUnit"
label = "Freight Storage Unit"
screens = ["Auto", "Teleop", "Endgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "autoBonus"
label = "Auto Bonus"
screens = ["Auto"]

[objectiveElements.field]
fieldType = "Dropdown"
options = ["None", "Team Shipping Element", "Duck"]

[[objectiveElements]]
name = "allianceShippingHubLevelOne"
label = "Alliance Hub 1"
screens = ["Teleop", "Endgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "allianceShippingHubLevelTwo"
label = "Alliance Hub 2"
screens = ["Teleop", "Endgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "allianceShippingHubLevelThree"
label = "Alliance Hub 3"
screens = ["Teleop", "Endgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "sharedShippingHub"
label = "Shared Shipping Hub"
screens = ["Teleop", "Endgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "allianceShippingHubBalanced"
label = "Alliance Hub Balanced"
screens = ["Postgame"]

[objectiveElements.field]
fieldType = "Boolean"

[[objectiveElements]]
name = "sharedShippingHubUnbalanced"
label = "Shared Hub Unbalanced (in favor)"
screens = ["Postgame"]

[objectiveElements.field]
fieldType = "Boolean"

[[objectiveElements]]
name = "capped"
label = "Capped"
screens = ["Postgame"]

[objectiveElements.field]
fieldType = "Boolean"

[[objectiveElements]]
name = "startingPosition"
label = "Starting Position"
screens = ["Pregame"]

[objectiveElements.field]
fieldType = "Dropdown"
options = ["Freightside", "Duckside"]

[[objectiveElements]]
name = "preload"
label = "Preload"
screens = ["Pregame"]

[objectiveElements.field]
fieldType = "Boolean"

[[objectiveElements]]
name = "rating"
label = "Rating"
screens = ["Postgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 1
max = 5
isInteger = true
incrementable = false
