#:schema ./schemas/game.schema.json
name = "FreightFrenzy"
description = "Ducks Balls Cubes FTC"
year = 2021
allianceSize = 3

[[subjectiveElements]]
name = "scoutId"
label = "Scout ID"
screens = ["SubjectiveInfo"]

[subjectiveElements.field]
fieldType = "Dropdown"
options = ["Red S", "Blue S"]

[[subjectiveElements]]
name = "matchType"
label = "Match Type"
screens = ["SubjectiveInfo"]

[subjectiveElements.field]
fieldType = "Dropdown"
options = ["Practice", "Qualification", "Quarterfinal", "Semifinal", "Final"]

[[subjectiveElements]]
name = "matchNumber"
label = "Match Number"
screens = ["SubjectiveInfo"]

[subjectiveElements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[subjectiveElements]]
name = "teamOneNumber"
label = "Team One Number"
screens = ["SubjectiveInfo"]

[subjectiveElements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[subjectiveElements]]
name = "teamTwoNumber"
label = "Team Two Number"
screens = ["SubjectiveInfo"]

[subjectiveElements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[subjectiveElements]]
name = "teamThreeNumber"
label = "Team Three Number"
screens = ["SubjectiveInfo"]

[subjectiveElements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[subjectiveElements]]
name = "scoutName"
label = "Scout Name"
screens = ["SubjectiveOther"]

[subjectiveElements.field]
fieldType = "Text"

[[objectiveElements]]
name = "scoutId"
label = "Scout ID"
screens = ["ObjectiveInfo"]

[objectiveElements.field]
fieldType = "Dropdown"
options = ["Red 1", "Red 2", "Red 3", "Blue 1", "Blue 2", "Blue 3"]

[[objectiveElements]]
name = "matchType"
label = "Match Type"
screens = ["ObjectiveInfo"]

[objectiveElements.field]
fieldType = "Dropdown"
options = ["Practice", "Qualification", "Quarterfinal", "Semifinal", "Final"]

[[objectiveElements]]
name = "matchNumber"
label = "Match Number"
screens = ["ObjectiveInfo"]

[objectiveElements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[objectiveElements]]
name = "teamNumber"
label = "Team Number"
screens = ["ObjectiveInfo"]

[objectiveElements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[objectiveElements]]
name = "scoutName"
label = "Scout Name"
screens = ["ObjectivePostgame"]

[objectiveElements.field]
fieldType = "Text"

[[objectiveElements]]
name = "duckDelivery"
label = "Duck Delivery"
screens = ["ObjectiveAuto", "ObjectiveEndgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "parking"
label = "Parking"
screens = ["ObjectiveAuto", "ObjectivePostgame"]

[objectiveElements.field]
fieldType = "Dropdown"
options = [
  "None",
  "Warehouse Fully",
  "Warehouse Partially (auto only)",
  "Storage Fully",
  "Storage Partially (auto only)",
]

[[objectiveElements]]
name = "freightShippingHub"
label = "Freight Shipping Hub (any level)"
screens = ["ObjectiveAuto"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "freightStorageUnit"
label = "Freight Storage Unit"
screens = ["ObjectiveAuto", "ObjectiveTeleop", "ObjectiveEndgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "autoBonus"
label = "Auto Bonus"
screens = ["ObjectiveAuto"]

[objectiveElements.field]
fieldType = "Dropdown"
options = ["None", "Team Shipping Element", "Duck"]

[[objectiveElements]]
name = "allianceShippingHubLevelOne"
label = "Alliance Hub 1"
screens = ["ObjectiveTeleop", "ObjectiveEndgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "allianceShippingHubLevelTwo"
label = "Alliance Hub 2"
screens = ["ObjectiveTeleop", "ObjectiveEndgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "allianceShippingHubLevelThree"
label = "Alliance Hub 3"
screens = ["ObjectiveTeleop", "ObjectiveEndgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "sharedShippingHub"
label = "Shared Shipping Hub"
screens = ["ObjectiveTeleop", "ObjectiveEndgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[objectiveElements]]
name = "allianceShippingHubBalanced"
label = "Alliance Hub Balanced"
screens = ["ObjectivePostgame"]

[objectiveElements.field]
fieldType = "Boolean"

[[objectiveElements]]
name = "sharedShippingHubUnbalanced"
label = "Shared Hub Unbalanced (in favor)"
screens = ["ObjectivePostgame"]

[objectiveElements.field]
fieldType = "Boolean"

[[objectiveElements]]
name = "capped"
label = "Capped"
screens = ["ObjectivePostgame"]

[objectiveElements.field]
fieldType = "Boolean"

[[objectiveElements]]
screens = ["ObjectivePregame"]
name = "startingPosition"
label = "Starting Position"

[objectiveElements.field]
fieldType = "Dropdown"
options = ["Freightside", "Duckside"]

[[objectiveElements]]
name = "preload"
label = "Preload"
screens = ["ObjectivePregame"]

[objectiveElements.field]
fieldType = "Boolean"

[[objectiveElements]]
name = "rating"
label = "Rating"
screens = ["ObjectivePostgame"]

[objectiveElements.field]
fieldType = "Numeric"
min = 1
max = 5
isInteger = true
incrementable = false

[[subjectiveElements]]
name = "notes"
label = "Notes"
screens = ["SubjectiveTeam"]

[subjectiveElements.field]
fieldType = "Text"

[[infoElements]]