#:schema https://raw.githubusercontent.com/omagarwal25/scouting-app/main/packages/game/schemas/game.schema.json
name = "FreightFrenzy"
description = "Ducks Balls Cubes FTC"
year = 2021
allianceSize = 3

[[elements]]
name = "scoutId"
label = "Scout ID"
screens = ["SubjectiveInfo"]

[elements.field]
fieldType = "Dropdown"
options = ["Red S", "Blue S"]

[[elements]]
name = "matchType"
label = "Match Type"
screens = ["SubjectiveInfo"]

[elements.field]
fieldType = "Dropdown"
options = ["Practice", "Qualification", "Quarterfinal", "Semifinal", "Final"]

[[elements]]
name = "matchNumber"
label = "Match Number"
screens = ["SubjectiveInfo"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[elements]]
name = "teamOneNumber"
label = "Team One Number"
screens = ["SubjectiveInfo"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[elements]]
name = "teamTwoNumber"
label = "Team Two Number"
screens = ["SubjectiveInfo"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[elements]]
name = "teamThreeNumber"
label = "Team Three Number"
screens = ["SubjectiveInfo"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[elements]]
name = "scoutName"
label = "Scout Name"
screens = ["SubjectiveOther"]

[elements.field]
fieldType = "Text"

[[elements]]
name = "scoutId"
label = "Scout ID"
screens = ["ObjectiveInfo"]

[elements.field]
fieldType = "Dropdown"
options = ["Red 1", "Red 2", "Red 3", "Blue 1", "Blue 2", "Blue 3"]

[[elements]]
name = "matchType"
label = "Match Type"
screens = ["ObjectiveInfo"]

[elements.field]
fieldType = "Dropdown"
options = ["Practice", "Qualification", "Quarterfinal", "Semifinal", "Final"]

[[elements]]
name = "matchNumber"
label = "Match Number"
screens = ["ObjectiveInfo"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[elements]]
name = "teamNumber"
label = "Team Number"
screens = ["ObjectiveInfo"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false
min = 0

[[elements]]
name = "scoutName"
label = "Scout Name"
screens = ["ObjectiveOther"]

[elements.field]
fieldType = "Text"

[[elements]]
name = "duckDelivery"
label = "Duck Delivery"
screens = ["ObjectiveAuto", "ObjectiveEndgame"]

[elements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[elements]]
name = "parking"
label = "Parking"
screens = ["ObjectiveAuto", "ObjectivePostgame"]

[elements.field]
fieldType = "Dropdown"
options = [
  "None",
  "Warehouse Fully",
  "Warehouse Partially (auto only)",
  "Storage Fully",
  "Storage Partially (auto only)",
]

[[elements]]
name = "freightShippingHub"
label = "Freight Shipping Hub (any level)"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[elements]]
name = "freightStorageUnit"
label = "Freight Storage Unit"
screens = ["ObjectiveAuto", "ObjectiveTeleop", "ObjectiveEndgame"]

[elements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[elements]]
name = "autoBonus"
label = "Auto Bonus"
screens = ["ObjectiveAuto"]

[elements.field]
fieldType = "Dropdown"
options = ["None", "Team Shipping Element", "Duck"]

[[elements]]
name = "allianceShippingHubLevelOne"
label = "Alliance Hub 1"
screens = ["ObjectiveTeleop", "ObjectiveEndgame"]

[elements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[elements]]
name = "allianceShippingHubLevelTwo"
label = "Alliance Hub 2"
screens = ["ObjectiveTeleop", "ObjectiveEndgame"]

[elements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[elements]]
name = "allianceShippingHubLevelThree"
label = "Alliance Hub 3"
screens = ["ObjectiveTeleop", "ObjectiveEndgame"]

[elements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[elements]]
name = "sharedShippingHub"
label = "Shared Shipping Hub"
screens = ["ObjectiveTeleop", "ObjectiveEndgame"]

[elements.field]
fieldType = "Numeric"
min = 0
isInteger = true
incrementable = true

[[elements]]
name = "allianceShippingHubBalanced"
label = "Alliance Hub Balanced"
screens = ["ObjectivePostgame"]

[elements.field]
fieldType = "Boolean"

[[elements]]
name = "sharedShippingHubUnbalanced"
label = "Shared Hub Unbalanced (in favor)"
screens = ["ObjectivePostgame"]

[elements.field]
fieldType = "Boolean"

[[elements]]
name = "capped"
label = "Capped"
screens = ["ObjectivePostgame"]

[elements.field]
fieldType = "Boolean"

[[elements]]
screens = ["ObjectivePregame"]
name = "startingPosition"
label = "Starting Position"

[elements.field]
fieldType = "Dropdown"
options = ["Freightside", "Duckside"]

[[elements]]
name = "preload"
label = "Preload"
screens = ["ObjectivePregame"]

[elements.field]
fieldType = "Boolean"

[[elements]]
name = "rating"
label = "Rating"
screens = ["ObjectiveOther"]

[elements.field]
fieldType = "Numeric"
min = 1
max = 5
isInteger = true
incrementable = false

[[elements]]
name = "notes"
label = "Notes"
screens = ["SubjectiveTeam"]

[elements.field]
fieldType = "Text"

[[elements]]
name = "teamNumber"
label = "Team Number"
screens = ["PitInfo"]

[elements.field]
fieldType = "Numeric"
isInteger = true
incrementable = false

[[elements]]
name = "scoutName"
label = "Scout Name"
screens = ["PitOther"]

[elements.field]
fieldType = "Text"

[[elements]]
name = "underBridge"
label = "Under Bridge"
screens = ["PitSpecifications"]

[elements.field]
fieldType = "Boolean"

[[elements]]
name = "can5Ball"
label = "Can 5 Ball"
screens = ["PitAuto"]

[elements.field]
fieldType = "Boolean"

[[elements]]
name = "preferedCycle"
label = "Prefered Cycle"
screens = ["PitTeleop"]

[elements.field]
fieldType = "Dropdown"
options = ["Freight", "Duck"]

[[elements]]
name = "canPark"
label = "Can Park"
screens = ["PitEndgame"]

[elements.field]
fieldType = "Boolean"

[[elements]]
name = "driveTrainType"
label = "Drive Train Type"
screens = ["PitDrive"]

[elements.field]
fieldType = "Dropdown"
options = ["Mecanum", "Omni", "Tank", "Swerve"]
